### ISSUE TITLE
NPE when processing QuaDramaCorpus

### ISSUE THREAD

**Issue by nilsreiter** [quadrama/DramaNLP#66]
I tried to convert the QuaDramACorpus into CSV with version 2.0, and I got a ton of these errors:
```
java.lang.NullPointerException                                                                                                                  
        at de.unistuttgart.quadrama.io.core.CSVVariant.convertStageDirections(CSVVariant.java:270)                                          
        at de.unistuttgart.quadrama.io.core.CSVVariant.convert(CSVVariant.java:103)                                                             
        at de.unistuttgart.quadrama.io.core.ExportAsCSV.process(ExportAsCSV.java:63)                                                        
        at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48)                                    
        at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:401)
        at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:318)
        at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:570)                  
        at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:412)                                 
        at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344)                                                     
        at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:271)    
        at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:570)              
        at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:412)                                     
        at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344)                                                     
        at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:271)
        at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:269)                                 
        at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:176)                                                 
        at de.unistuttgart.ims.drama.main.TEI2XMI.main(TEI2XMI.java:137)  
```

**Comment by pagelj** [comment]
Fixed in https://github.com/quadrama/DramaNLP/releases/tag/v.2.0.1
